version: "3.9"

services:
  rag_service:
    build: ./rag_service
    container_name: rag_service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - python_network
      - oguncarpentry_mcp_network

  docling_service:
    build: ./docling_service
    container_name: docling_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - python_network
      - oguncarpentry_mcp_network

networks:
  python_network:
    driver: bridge
    external: false
  oguncarpentry_mcp_network:
    external: true

volumes:
  python_data: